
GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS code rest client is a pretty handy tool",
  "important": true
}

###

DELETE http://localhost:3001/api/notes/6884ee28dcbe95d983e43ff9

###
PUT http://localhost:3001/api/notes/6884ee11fcc7b6f2e1b5599f
Content-Type: application/json

{
  "content": "VS code rest client is a pretty handy tool",
  "important": true 
}