
###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "TEST title",
  "author": "Test author",
  "url": "TestUrl.com",
  "likes": 5
}